In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_json('../Data/hang.json')

In [4]:
data

              success  code                                               data
carSales         True    10  [{'id': 89213, 'category_id': 1209, 'hash_url'...
totalRecords     True    10                                              89020

In [115]:
res = pd.DataFrame(data.data[0])

In [116]:
res

,id,category_id,hash_url,url,thumbnail,seller_location,car_title,car_year,car_price,car_origin,...,car_color,car_fuel,car_doors,car_seats,car_gearbox,car_mileage,car_engine,createdAt,updatedAt,category
0,89213,1209,425c72964240a06284ae30302c7b0193,https://bonbanh.com/xe-thaco-ollin--2017-4070159,https://cdn.muaotocu.info/file/crash-finder/ca...,Gia Lai,Thaco Ollin - 2017,2017,290000000,Lắp ráp trong nước,...,Xanh,Dầu,2.0,3.0,Số tay,0.0,None,2021-11-06T17:28:03.000Z,2021-11-06T23:06:45.000Z,"{'id': 1209, 'car_model_id': 1209, 'source_id'..."
1,89212,1140,9d5df158e407a696d94092c62216afe0,https://bonbanh.com/xe-rolls_royce-cullinan--2...,https://cdn.muaotocu.info/file/crash-finder/ca...,TP HCM,Rolls Royce Cullinan - 2020,2020,18800000000,Nhập khẩu,...,Đen,Xăng,4.0,5.0,Số tự động,9000.0,None,2021-11-06T17:27:38.000Z,2021-11-06T23:06:45.000Z,"{'id': 1140, 'car_model_id': 1140, 'source_id'..."
2,89211,1064,c84c731c3a5ae56eefc19459559a1e2d,https://bonbanh.com/xe-maserati-levante-gran-l...,None,TP HCM,Maserati Levante gran lusso - 2017,2017,4500000000,Nhập khẩu,...,Xám,Xăng,4.0,5.0,Số tự động,24500.0,None,2021-11-06T17:27:14.000Z,2021-11-06T23:06:44.000Z,"{'id': 1064, 'car_model_id': 1064, 'source_id'..."
3,89210,1043,4e7ed45f7d25b69215c8937e1cfddca7,https://bonbanh.com/xe-lifan-520-1.6-mt-2007-4...,https://cdn.muaotocu.info/file/crash-finder/ca...,Thanh Hóa,Lifan 520 1.6 MT - 2007,2007,32000000,Lắp ráp trong nước,...,Cát,Xăng 1.6 L,4.0,5.0,Số tay,0.0,None,2021-11-06T17:27:08.000Z,2021-11-06T23:06:46.000Z,"{'id': 1043, 'car_model_id': 1043, 'source_id'..."
4,89209,998,00af56b82479323d7bbe430e0d107119,https://bonbanh.com/xe-jaguar-xj_series-xjl-3....,https://cdn.muaotocu.info/file/crash-finder/ca...,Hà Nội,Jaguar XJ series XJL 3.0 Supercharged - 2014,2014,1990000000,Nhập khẩu,...,Trắng,Xăng,4.0,5.0,Số hỗn hợp,60000.0,None,2021-11-06T17:26:58.000Z,2021-11-06T23:06:45.000Z,"{'id': 998, 'car_model_id': 998, 'source_id': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89015,9,1,0f4626198e917ab3a064207579f50db9,https://bonbanh.com/xe-acura-mdx-sh-awd-2010-3...,https://cdn.muaotocu.info/file/crash-finder/ca...,Hà Nội,Acura MDX SH-AWD - 2010,2010,830000000,Nhập khẩu,...,Đen,Xăng 3.7 L,5.0,7.0,Số tự động,0.0,None,2021-09-29T17:52:46.000Z,2021-09-30T12:22:45.000Z,"{'id': 1, 'car_model_id': 1, 'source_id': 1, '..."
89016,10,1,686480cd6d20bd40d4d9bb1bed169202,https://bonbanh.com/xe-acura-mdx-3.5-at-2003-3...,https://cdn.muaotocu.info/file/crash-finder/ca...,TP HCM,Acura MDX 3.5 AT - 2003,2003,300000000,Nhập khẩu,...,Xanh,Xăng 3.5 L,5.0,7.0,Số tự động,95000.0,None,2021-09-29T17:52:46.000Z,2021-09-30T12:22:43.000Z,"{'id': 1, 'car_model_id': 1, 'source_id': 1, '..."
89017,11,1,4e37bd4b6c844c4e37c094fbbe2b348a,https://bonbanh.com/xe-acura-mdx-sh-awd-2008-3...,https://cdn.muaotocu.info/file/crash-finder/ca...,Hà Nội,Acura MDX SH-AWD - 2008,2008,499000000,Nhập khẩu,...,Bạc,Xăng 3.7 L,5.0,7.0,Số tự động,100000.0,None,2021-09-29T17:52:46.000Z,2021-09-30T12:22:48.000Z,"{'id': 1, 'car_model_id': 1, 'source_id': 1, '..."
89018,12,1,99d1f00249970971498c22e5956820ca,https://bonbanh.com/xe-acura-mdx-sh-awd-2008-3...,https://cdn.muaotocu.info/file/crash-finder/ca...,Hà Nội,Acura MDX SH-AWD - 2008,2008,499000000,Nhập khẩu,...,Đen,Xăng 3.7 L,5.0,7.0,Số tự động,100000.0,None,2021-09-29T17:52:46.000Z,2021-09-30T12:22:45.000Z,"{'id': 1, 'car_model_id': 1, 'source_id': 1, '..."
89019,13,1,27304261ddb8cc806fa8f3f56e7237d3,https://bonbanh.com/xe-acura-mdx-sh-awd-2008-3...,https://cdn.muaotocu.info/file/crash-finder/ca...,TP HCM,Acura MDX SH-AWD - 2008,2008,450000000,Nhập khẩu,...,Đen,Xăng 3.7 L,5.0,7.0,Số tự động,84000.0,None,2021-09-29T17:52:46.000Z,2021-09-30T12:22:45.000Z,"{'id': 1, 'car_model_id': 1, 'source_id': 1, '..."

In [117]:
#filter only web bonbanh

In [118]:
res = res[res['url'].str[8:15] =='bonbanh']

In [119]:
res.reset_index(inplace=True,drop=True)

In [120]:
res

,id,category_id,hash_url,url,thumbnail,seller_location,car_title,car_year,car_price,car_origin,...,car_color,car_fuel,car_doors,car_seats,car_gearbox,car_mileage,car_engine,createdAt,updatedAt,category
0,89213,1209,425c72964240a06284ae30302c7b0193,https://bonbanh.com/xe-thaco-ollin--2017-4070159,https://cdn.muaotocu.info/file/crash-finder/ca...,Gia Lai,Thaco Ollin - 2017,2017,290000000,Lắp ráp trong nước,...,Xanh,Dầu,2.0,3.0,Số tay,0.0,None,2021-11-06T17:28:03.000Z,2021-11-06T23:06:45.000Z,"{'id': 1209, 'car_model_id': 1209, 'source_id'..."
1,89212,1140,9d5df158e407a696d94092c62216afe0,https://bonbanh.com/xe-rolls_royce-cullinan--2...,https://cdn.muaotocu.info/file/crash-finder/ca...,TP HCM,Rolls Royce Cullinan - 2020,2020,18800000000,Nhập khẩu,...,Đen,Xăng,4.0,5.0,Số tự động,9000.0,None,2021-11-06T17:27:38.000Z,2021-11-06T23:06:45.000Z,"{'id': 1140, 'car_model_id': 1140, 'source_id'..."
2,89211,1064,c84c731c3a5ae56eefc19459559a1e2d,https://bonbanh.com/xe-maserati-levante-gran-l...,None,TP HCM,Maserati Levante gran lusso - 2017,2017,4500000000,Nhập khẩu,...,Xám,Xăng,4.0,5.0,Số tự động,24500.0,None,2021-11-06T17:27:14.000Z,2021-11-06T23:06:44.000Z,"{'id': 1064, 'car_model_id': 1064, 'source_id'..."
3,89210,1043,4e7ed45f7d25b69215c8937e1cfddca7,https://bonbanh.com/xe-lifan-520-1.6-mt-2007-4...,https://cdn.muaotocu.info/file/crash-finder/ca...,Thanh Hóa,Lifan 520 1.6 MT - 2007,2007,32000000,Lắp ráp trong nước,...,Cát,Xăng 1.6 L,4.0,5.0,Số tay,0.0,None,2021-11-06T17:27:08.000Z,2021-11-06T23:06:46.000Z,"{'id': 1043, 'car_model_id': 1043, 'source_id'..."
4,89209,998,00af56b82479323d7bbe430e0d107119,https://bonbanh.com/xe-jaguar-xj_series-xjl-3....,https://cdn.muaotocu.info/file/crash-finder/ca...,Hà Nội,Jaguar XJ series XJL 3.0 Supercharged - 2014,2014,1990000000,Nhập khẩu,...,Trắng,Xăng,4.0,5.0,Số hỗn hợp,60000.0,None,2021-11-06T17:26:58.000Z,2021-11-06T23:06:45.000Z,"{'id': 998, 'car_model_id': 998, 'source_id': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65089,9,1,0f4626198e917ab3a064207579f50db9,https://bonbanh.com/xe-acura-mdx-sh-awd-2010-3...,https://cdn.muaotocu.info/file/crash-finder/ca...,Hà Nội,Acura MDX SH-AWD - 2010,2010,830000000,Nhập khẩu,...,Đen,Xăng 3.7 L,5.0,7.0,Số tự động,0.0,None,2021-09-29T17:52:46.000Z,2021-09-30T12:22:45.000Z,"{'id': 1, 'car_model_id': 1, 'source_id': 1, '..."
65090,10,1,686480cd6d20bd40d4d9bb1bed169202,https://bonbanh.com/xe-acura-mdx-3.5-at-2003-3...,https://cdn.muaotocu.info/file/crash-finder/ca...,TP HCM,Acura MDX 3.5 AT - 2003,2003,300000000,Nhập khẩu,...,Xanh,Xăng 3.5 L,5.0,7.0,Số tự động,95000.0,None,2021-09-29T17:52:46.000Z,2021-09-30T12:22:43.000Z,"{'id': 1, 'car_model_id': 1, 'source_id': 1, '..."
65091,11,1,4e37bd4b6c844c4e37c094fbbe2b348a,https://bonbanh.com/xe-acura-mdx-sh-awd-2008-3...,https://cdn.muaotocu.info/file/crash-finder/ca...,Hà Nội,Acura MDX SH-AWD - 2008,2008,499000000,Nhập khẩu,...,Bạc,Xăng 3.7 L,5.0,7.0,Số tự động,100000.0,None,2021-09-29T17:52:46.000Z,2021-09-30T12:22:48.000Z,"{'id': 1, 'car_model_id': 1, 'source_id': 1, '..."
65092,12,1,99d1f00249970971498c22e5956820ca,https://bonbanh.com/xe-acura-mdx-sh-awd-2008-3...,https://cdn.muaotocu.info/file/crash-finder/ca...,Hà Nội,Acura MDX SH-AWD - 2008,2008,499000000,Nhập khẩu,...,Đen,Xăng 3.7 L,5.0,7.0,Số tự động,100000.0,None,2021-09-29T17:52:46.000Z,2021-09-30T12:22:45.000Z,"{'id': 1, 'car_model_id': 1, 'source_id': 1, '..."
65093,13,1,27304261ddb8cc806fa8f3f56e7237d3,https://bonbanh.com/xe-acura-mdx-sh-awd-2008-3...,https://cdn.muaotocu.info/file/crash-finder/ca...,TP HCM,Acura MDX SH-AWD - 2008,2008,450000000,Nhập khẩu,...,Đen,Xăng 3.7 L,5.0,7.0,Số tự động,84000.0,None,2021-09-29T17:52:46.000Z,2021-09-30T12:22:45.000Z,"{'id': 1, 'car_model_id': 1, 'source_id': 1, '..."

In [121]:
def dict_to_frame(data,colName):
    data = list(data[colName])
    return pd.DataFrame(data)

In [122]:
res1 = dict_to_frame(res,'category')
res1

,id,car_model_id,source_id,source,car_model
0,1209,1209,1,"{'id': 1, 'url': 'https://bonbanh.com', 'name'...","{'id': 1209, 'manufacturer_id': 80, 'model': '..."
1,1140,1140,1,"{'id': 1, 'url': 'https://bonbanh.com', 'name'...","{'id': 1140, 'manufacturer_id': 71, 'model': '..."
2,1064,1064,1,"{'id': 1, 'url': 'https://bonbanh.com', 'name'...","{'id': 1064, 'manufacturer_id': 59, 'model': '..."
3,1043,1043,1,"{'id': 1, 'url': 'https://bonbanh.com', 'name'...","{'id': 1043, 'manufacturer_id': 56, 'model': '..."
4,998,998,1,"{'id': 1, 'url': 'https://bonbanh.com', 'name'...","{'id': 998, 'manufacturer_id': 51, 'model': 'X..."
...,...,...,...,...,...
65089,1,1,1,"{'id': 1, 'url': 'https://bonbanh.com', 'name'...","{'id': 1, 'manufacturer_id': 1, 'model': 'MDX'..."
65090,1,1,1,"{'id': 1, 'url': 'https://bonbanh.com', 'name'...","{'id': 1, 'manufacturer_id': 1, 'model': 'MDX'..."
65091,1,1,1,"{'id': 1, 'url': 'https://bonbanh.com', 'name'...","{'id': 1, 'manufacturer_id': 1, 'model': 'MDX'..."
65092,1,1,1,"{'id': 1, 'url': 'https://bonbanh.com', 'name'...","{'id': 1, 'manufacturer_id': 1, 'model': 'MDX'..."
65093,1,1,1,"{'id': 1, 'url': 'https://bonbanh.com', 'name'...","{'id': 1, 'manufacturer_id': 1, 'model': 'MDX'..."

In [123]:
res2 = dict_to_frame(res1,'source')
res2

,id,url,name,logo,favicon
0,1,https://bonbanh.com,Bonbanh.com,https://crash-finder.s3.us-west-002.backblazeb...,https://crash-finder.s3.us-west-002.backblazeb...
1,1,https://bonbanh.com,Bonbanh.com,https://crash-finder.s3.us-west-002.backblazeb...,https://crash-finder.s3.us-west-002.backblazeb...
2,1,https://bonbanh.com,Bonbanh.com,https://crash-finder.s3.us-west-002.backblazeb...,https://crash-finder.s3.us-west-002.backblazeb...
3,1,https://bonbanh.com,Bonbanh.com,https://crash-finder.s3.us-west-002.backblazeb...,https://crash-finder.s3.us-west-002.backblazeb...
4,1,https://bonbanh.com,Bonbanh.com,https://crash-finder.s3.us-west-002.backblazeb...,https://crash-finder.s3.us-west-002.backblazeb...
...,...,...,...,...,...
65089,1,https://bonbanh.com,Bonbanh.com,https://crash-finder.s3.us-west-002.backblazeb...,https://crash-finder.s3.us-west-002.backblazeb...
65090,1,https://bonbanh.com,Bonbanh.com,https://crash-finder.s3.us-west-002.backblazeb...,https://crash-finder.s3.us-west-002.backblazeb...
65091,1,https://bonbanh.com,Bonbanh.com,https://crash-finder.s3.us-west-002.backblazeb...,https://crash-finder.s3.us-west-002.backblazeb...
65092,1,https://bonbanh.com,Bonbanh.com,https://crash-finder.s3.us-west-002.backblazeb...,https://crash-finder.s3.us-west-002.backblazeb...
65093,1,https://bonbanh.com,Bonbanh.com,https://crash-finder.s3.us-west-002.backblazeb...,https://crash-finder.s3.us-west-002.backblazeb...

In [124]:
res3 = dict_to_frame(res1,'car_model')
res3

         id  manufacturer_id      model                 cname
0      1209               80      Ollin           Thaco Ollin
1      1140               71   Cullinan  Rolls Royce Cullinan
2      1064               59    Levante      Maserati Levante
3      1043               56        520             Lifan 520
4       998               51  XJ Series      Jaguar XJ Series
...     ...              ...        ...                   ...
65089     1                1        MDX             Acura MDX
65090     1                1        MDX             Acura MDX
65091     1                1        MDX             Acura MDX
65092     1                1        MDX             Acura MDX
65093     1                1        MDX             Acura MDX

[65094 rows x 4 columns]

In [125]:
result = pd.concat([res,res1[['id','car_model_id','source_id']],res3],axis=1)

In [127]:
result.drop(columns='category',inplace=True)

In [129]:
result.to_csv('../Data/data_bonbanh.csv',index=False)

In [139]:
result.loc[0]

id                                                             89213
category_id                                                     1209
hash_url                            425c72964240a06284ae30302c7b0193
url                 https://bonbanh.com/xe-thaco-ollin--2017-4070159
thumbnail          https://cdn.muaotocu.info/file/crash-finder/ca...
seller_location                                              Gia Lai
car_title                                         Thaco Ollin - 2017
car_year                                                        2017
car_price                                                  290000000
car_origin                                        Lắp ráp trong nước
car_condition                                             Xe đã dùng
car_type                                                       Truck
car_color                                                       Xanh
car_fuel                                                         Dầu
car_doors                                                        2.0
car_seats                                                        3.0
car_gearbox                                                   Số tay
car_mileage                                                      0.0
car_engine                                                      None
createdAt                                   2021-11-06T17:28:03.000Z
updatedAt                                   2021-11-06T23:06:45.000Z
id                                                              1209
car_model_id                                                    1209
source_id                                                          1
id                                                              1209
manufacturer_id                                                   80
model                                                          Ollin
cname                                                    Thaco Ollin
Name: 0, dtype: object

In [138]:
result.seller_location.unique()

array(['Gia Lai', 'TP HCM', 'Thanh Hóa', 'Hà Nội', 'Đồng Nai',
       'Bình Dương', 'Lâm Đồng', 'An Giang', 'Hải Phòng', 'Cần Thơ',
       'Bắc Ninh', 'Tây Ninh', 'Bắc Giang', 'Tiền Giang', 'Đăk Lăk',
       'Đồng Tháp', 'Sóc Trăng', 'Bà Rịa Vũng Tàu', 'Đà Nẵng',
       'Vĩnh Phúc', 'Nghệ An', 'Phú Thọ', 'Hải Dương', 'Yên Bái',
       'Điện Biên', 'Nam Định', 'Khánh Hòa', 'Bình Thuận', 'Ninh Bình',
       'Bắc Kạn', 'Vĩnh Long', 'Sơn La', 'Thái Bình', 'Quảng Ninh',
       'Thái Nguyên', 'Hưng Yên', 'Cao Bằng', 'Quảng Trị', 'Bình Định',
       'Kon Tum', 'Hà Nam', 'Hà Tĩnh', 'Thừa Thiên Huế', 'Quảng Ngãi',
       'Bình Phước', 'Lạng Sơn', 'Quảng Bình', 'Đăk Nông', 'Phú Yên',
       'Hậu Giang', 'Long An', 'Quảng Nam', 'Bến Tre', 'Kiên Giang',
       'Lào Cai', 'Hòa Bình', 'Tuyên Quang', 'Bạc Liêu', 'Hà Giang',
       'Trà Vinh', 'Cà Mau', 'Ninh Thuận', 'Lai Châu'], dtype=object)